modules:
  - type: files
    files:
      - usr: /usr

  - type: script
    snippets:
      - "curl -sS https://starship.rs/install.sh | sh -s -- -b /usr/bin --verbose --yes"
      - "chmod +x /usr/bin/*"
  
  - type: rpm-ostree
    install:
      - adwaita-gtk2-theme
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.discordapp.Discord
        - com.github.jeromerobert.pdfarranger
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - com.valvesoftware.Steam
        - md.obsidian.Obsidian
        - org.chromium.Chromium
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.gnome.Calculator
        - org.gnome.Firmware
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.eog
        - org.gnome.meld
        - org.gtk.Gtk3theme.Adwaita-dark
        - org.inkscape.Inkscape
        - org.kde.okular
        - org.mozilla.firefox
        - org.videolan.VLC
      remove:
        # - org.gnome.eog

  - type: systemd
    user:
      enabled:
        - kanshi.service

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro

  - type: gschema-overrides
    include:
      - zz1.gschema.override 

  - type: signing
