modules:
  - type: files
    files:
      - usr: /usr

  - type: script
    snippets:
      - "chmod +x /usr/bin/*"

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
      - neovim
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - com.valvesoftware.Steam
        - com.discordapp.Discord
        - org.gnome.Calculator
        - md.obsidian.Obsidian
        - org.gimp.GIMP
        - org.inkscape.Inkscape
        - org.gnome.baobab
        - org.fedoraproject.MediaWriter
        - org.kde.okular
      remove:
        # - org.gnome.eog

  - type: systemd
    user:
      enabled:
        - kanshi.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing
