modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo 
    install:
      - starship
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - com.valvesoftware.Steam
        - com.discordapp.Discord
        - org.gnome.Calculator
        - org.kde.okular
      remove:
        # - org.gnome.eog

  - type: signing
