modules:
  #- type: akmods
  #  install:
  #    - v4l2loopback

  - type: files
    files:
      - usr: /usr

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:main-40 /rpms/ /tmp/rpms
      - RUN find /tmp/rpms
      - RUN rpm-ostree install /tmp/rpms/ublue-os/ublue-os-akmods*.rpm
      - RUN rpm-ostree install /tmp/rpms/kmods/kmod-v4l2loopback*.rpm

  - type: rpm-ostree
    install:
      - adwaita-gtk2-theme
      - libadwaita
      - akmod-intel-ipu6
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.discordapp.Discord
        - com.github.jeromerobert.pdfarranger
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - com.valvesoftware.Steam
        - com.protonvpn.www
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.gnome.Calculator
        - org.gnome.Firmware
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.Loupe
        - org.gnome.meld
        - org.gtk.Gtk3theme.Adwaita-dark
        - org.inkscape.Inkscape
        - org.kde.okular
        - org.mozilla.firefox
        - org.videolan.VLC

  - type: systemd
    user:
      enabled:
        - kanshi.service

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro

  - type: gschema-overrides
    include:
      - zz1.gschema.override

  - type: signing
