modules:
  # - type: ipu6
  #   option: true
  #   other: rstrst
  #   there: "123123"

  - type: akmods
    install:
      - v4l2loopback

  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - adwaita-gtk2-theme
      - libadwaita
      - akmod-intel-ipu6
    remove:
      - firefox
      - firefox-langpacks

  - type: script
    snippets:
      - 'akmods --force --kernels "6.8.7-300.fc40.x86_64" --kmod intel-ipu6'
      - "ln -s /usr/bin/podman /usr/bin/docker"
      - "chmod +x /usr/bin/*"

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - com.discordapp.Discord
        - com.github.jeromerobert.pdfarranger
        - com.github.tchx84.Flatseal
        - com.slack.Slack
        - com.valvesoftware.Steam
        - com.protonvpn.www
        #- md.obsidian.Obsidian
        #- org.chromium.Chromium
        - org.fedoraproject.MediaWriter
        - org.gimp.GIMP
        - org.gnome.Calculator
        - org.gnome.Firmware
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.baobab
        - org.gnome.Loupe
        #- org.gnome.eog
        - org.gnome.meld
        - org.gtk.Gtk3theme.Adwaita-dark
        - org.inkscape.Inkscape
        - org.kde.okular
        - org.mozilla.firefox
        - org.videolan.VLC
  #     remove:
  #       # - org.gnome.eog

  - type: systemd
    user:
      enabled:
        - kanshi.service

  - type: fonts
    fonts:
      nerd-fonts:
        - DejaVuSansMono
        - FiraCode
        - Hack
        - JetBrainsMono
        - SourceCodePro

  - type: gschema-overrides
    include:
      - zz1.gschema.override

  - type: signing
